-- Reconstructed from the application's database contracts.
-- Contains schema and authorization rules only; no production user data.

create extension if not exists pgcrypto with schema extensions;

create type public.app_role as enum ('student', 'coach', 'admin', 'parent');
create type public.enrollment_status as enum ('active', 'inactive', 'pending');
create type public.quest_status as enum ('active', 'completed', 'expired');

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'student',
  locale text not null default 'es' check (locale in ('es', 'en', 'ca')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.programs (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  coach_id uuid references public.profiles(user_id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coach_programs (
  id bigint generated by default as identity primary key,
  coach_id uuid not null references public.profiles(user_id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (coach_id, program_id)
);

create table public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  status public.enrollment_status not null default 'active',
  enrolled_at timestamptz not null default now(),
  unique (user_id, program_id)
);

create table public.attendance_sessions (
  id bigint generated by default as identity primary key,
  program_id bigint references public.programs(id) on delete cascade,
  start_at timestamptz not null default now(),
  end_at timestamptz,
  expires_at timestamptz,
  qr_key text not null default encode(extensions.gen_random_bytes(24), 'hex'),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_at is null or end_at > start_at)
);

create table public.attendance_logs (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(user_id) on delete cascade,
  session_id bigint not null references public.attendance_sessions(id) on delete cascade,
  program_id bigint references public.programs(id) on delete set null,
  checked_at timestamptz not null default now(),
  marked_by uuid references public.profiles(user_id) on delete set null,
  unique (student_id, session_id)
);

-- Compatibility alias for one legacy delete path in the application.
create view public.attendance
with (security_invoker = true)
as select * from public.attendance_logs;

create table public.training_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  session_type text not null,
  duration_min integer not null check (duration_min > 0 and duration_min <= 1440),
  notes text,
  created_at timestamptz not null default now()
);

create table public.badges (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  icon_url text,
  created_at timestamptz not null default now()
);

create table public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  granted_at timestamptz not null default now(),
  unique (user_id, badge_id)
);

create table public.quests (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text not null default '',
  xp_reward integer not null default 0 check (xp_reward >= 0),
  steps jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.user_quests (
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  quest_id bigint not null references public.quests(id) on delete cascade,
  progress jsonb not null default '{}'::jsonb,
  status public.quest_status not null default 'active',
  assigned_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (user_id, quest_id)
);

create index programs_coach_id_idx on public.programs(coach_id);
create index coach_programs_program_id_idx on public.coach_programs(program_id);
create index enrollments_program_status_idx on public.enrollments(program_id, status);
create index enrollments_user_status_idx on public.enrollments(user_id, status);
create index attendance_sessions_program_start_idx on public.attendance_sessions(program_id, start_at);
create index attendance_logs_student_checked_idx on public.attendance_logs(student_id, checked_at desc);
create index attendance_logs_session_idx on public.attendance_logs(session_id);
create index training_logs_user_created_idx on public.training_logs(user_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

create trigger programs_touch_updated_at
before update on public.programs
for each row execute function public.touch_updated_at();

create trigger attendance_sessions_touch_updated_at
before update on public.attendance_sessions
for each row execute function public.touch_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.is_program_coach(p_program_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_admin() or exists (
    select 1
    from public.programs p
    where p.id = p_program_id and p.coach_id = auth.uid()
  ) or exists (
    select 1
    from public.coach_programs cp
    where cp.program_id = p_program_id and cp.coach_id = auth.uid()
  );
$$;

create or replace function public.is_program_member(p_program_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.enrollments e
    where e.program_id = p_program_id
      and e.user_id = auth.uid()
      and e.status = 'active'
  );
$$;

create or replace function public.xp_summary_for_user(p_user uuid)
returns table(total_xp bigint, event_type text, event_xp bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  with events as (
    select 'training_log'::text as event_type, count(*)::bigint * 10 as event_xp
    from public.training_logs where user_id = p_user
    union all
    select 'attendance_present'::text, count(*)::bigint * 20
    from public.attendance_logs where student_id = p_user
    union all
    select 'quest_completed'::text, coalesce(sum(q.xp_reward), 0)::bigint
    from public.user_quests uq
    join public.quests q on q.id = uq.quest_id
    where uq.user_id = p_user and uq.status = 'completed'
  )
  select sum(event_xp) over ()::bigint, event_type, event_xp from events;
$$;

create or replace function public.current_streak_days(p_user uuid)
returns integer
language sql
stable
security invoker
set search_path = ''
as $$
  with activity_days as (
    select distinct created_at::date as day
    from public.training_logs where user_id = p_user
    union
    select distinct checked_at::date
    from public.attendance_logs where student_id = p_user
  ),
  ranked as (
    select day, day - row_number() over (order by day)::integer as grp
    from activity_days
    where day <= current_date
  )
  select coalesce(max(streak), 0)::integer
  from (
    select count(*) as streak
    from ranked
    group by grp
    having max(day) >= current_date - 1
  ) s;
$$;

create or replace function public.leaderboard_top(limit_n integer default 10)
returns table(user_id uuid, full_name text, total_xp bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  with xp as (
    select p.user_id, p.full_name,
      (select count(*) * 10 from public.training_logs t where t.user_id = p.user_id)
      + (select count(*) * 20 from public.attendance_logs a where a.student_id = p.user_id)
      + (select coalesce(sum(q.xp_reward), 0)
         from public.user_quests uq join public.quests q on q.id = uq.quest_id
         where uq.user_id = p.user_id and uq.status = 'completed') as total_xp
    from public.profiles p
    where p.role = 'student'
  )
  select xp.user_id, xp.full_name, xp.total_xp::bigint
  from xp order by xp.total_xp desc, xp.full_name nulls last
  limit greatest(1, least(coalesce(limit_n, 10), 100));
$$;

create or replace function public.upcoming_sessions_for_user(
  p_user uuid,
  limit_n integer default 5
)
returns table(
  id bigint,
  program_id bigint,
  program_name text,
  start_at timestamptz,
  end_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select s.id, s.program_id, p.name, s.start_at, s.end_at
  from public.attendance_sessions s
  join public.programs p on p.id = s.program_id
  join public.enrollments e on e.program_id = s.program_id
  where e.user_id = p_user
    and e.status = 'active'
    and s.active
    and coalesce(s.end_at, s.start_at) >= now()
  order by s.start_at
  limit greatest(1, least(coalesce(limit_n, 5), 100));
$$;

create or replace function public.check_in_attendance(
  p_session_id bigint,
  p_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  target_session public.attendance_sessions%rowtype;
  inserted_id bigint;
begin
  if current_user_id is null then
    return jsonb_build_object('ok', false, 'error', 'unauthorized');
  end if;

  select * into target_session
  from public.attendance_sessions
  where id = p_session_id;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'session_not_found');
  end if;
  if not target_session.active then
    return jsonb_build_object('ok', false, 'error', 'session_inactive');
  end if;
  if target_session.expires_at is not null and now() > target_session.expires_at then
    return jsonb_build_object('ok', false, 'error', 'session_expired');
  end if;
  if now() < target_session.start_at then
    return jsonb_build_object('ok', false, 'error', 'session_not_started');
  end if;
  if target_session.end_at is not null and now() > target_session.end_at then
    return jsonb_build_object('ok', false, 'error', 'session_closed');
  end if;
  if p_key is null or p_key <> target_session.qr_key then
    return jsonb_build_object('ok', false, 'error', 'invalid_key');
  end if;
  if not exists (
    select 1 from public.enrollments
    where user_id = current_user_id
      and program_id = target_session.program_id
      and status = 'active'
  ) then
    return jsonb_build_object('ok', false, 'error', 'not_enrolled');
  end if;

  insert into public.attendance_logs (student_id, session_id, program_id)
  values (current_user_id, target_session.id, target_session.program_id)
  on conflict (student_id, session_id) do nothing
  returning id into inserted_id;

  return jsonb_build_object(
    'ok', true,
    'status', 'present',
    'xp', 20,
    'duplicate', inserted_id is null
  );
end;
$$;

create or replace function public.coach_session_qr(p_session_id bigint)
returns table(
  id bigint,
  qr_key text,
  expires_at timestamptz,
  start_at timestamptz,
  end_at timestamptz,
  active boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select s.id, s.qr_key, s.expires_at, s.start_at, s.end_at, s.active
  from public.attendance_sessions s
  where s.id = p_session_id
    and public.is_program_coach(s.program_id);
$$;

alter table public.profiles enable row level security;
alter table public.programs enable row level security;
alter table public.coach_programs enable row level security;
alter table public.enrollments enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.training_logs enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.quests enable row level security;
alter table public.user_quests enable row level security;

create policy profiles_read on public.profiles for select to authenticated
using (
  user_id = auth.uid() or public.is_admin() or exists (
    select 1 from public.enrollments e
    where e.user_id = profiles.user_id and public.is_program_coach(e.program_id)
  )
);
create policy profiles_update_own on public.profiles for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy programs_read on public.programs for select to authenticated
using (active or public.is_program_coach(id) or public.is_program_member(id));
create policy programs_manage on public.programs for all to authenticated
using (public.is_program_coach(id))
with check (public.is_admin() or coach_id = auth.uid());

create policy coach_programs_read on public.coach_programs for select to authenticated
using (coach_id = auth.uid() or public.is_admin());
create policy coach_programs_manage on public.coach_programs for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy enrollments_read on public.enrollments for select to authenticated
using (user_id = auth.uid() or public.is_program_coach(program_id));
create policy enrollments_manage on public.enrollments for all to authenticated
using (public.is_program_coach(program_id))
with check (public.is_program_coach(program_id));

create policy sessions_read on public.attendance_sessions for select to authenticated
using (public.is_program_coach(program_id) or public.is_program_member(program_id));
create policy sessions_manage on public.attendance_sessions for all to authenticated
using (public.is_program_coach(program_id))
with check (public.is_program_coach(program_id));

create policy attendance_read on public.attendance_logs for select to authenticated
using (student_id = auth.uid() or public.is_program_coach(program_id));
create policy attendance_insert_self on public.attendance_logs for insert to authenticated
with check (
  student_id = auth.uid()
  and public.is_program_member(program_id)
);
create policy attendance_manage_coach on public.attendance_logs for all to authenticated
using (public.is_program_coach(program_id))
with check (public.is_program_coach(program_id));

create policy training_logs_own on public.training_logs for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy badges_read on public.badges for select to authenticated using (true);
create policy badges_admin on public.badges for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy user_badges_read on public.user_badges for select to authenticated
using (user_id = auth.uid() or public.is_admin());
create policy user_badges_admin on public.user_badges for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy quests_read on public.quests for select to authenticated using (active or public.is_admin());
create policy quests_admin on public.quests for all to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy user_quests_read on public.user_quests for select to authenticated
using (user_id = auth.uid() or public.is_admin());
create policy user_quests_admin on public.user_quests for all to authenticated
using (public.is_admin()) with check (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
revoke update on public.profiles from authenticated;
grant update (full_name, locale) on public.profiles to authenticated;
revoke select on public.attendance_sessions from authenticated;
grant select (
  id,
  program_id,
  start_at,
  end_at,
  expires_at,
  active,
  created_at,
  updated_at
) on public.attendance_sessions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_program_coach(bigint) to authenticated;
grant execute on function public.is_program_member(bigint) to authenticated;
grant execute on function public.xp_summary_for_user(uuid) to authenticated;
grant execute on function public.current_streak_days(uuid) to authenticated;
grant execute on function public.leaderboard_top(integer) to authenticated;
grant execute on function public.upcoming_sessions_for_user(uuid, integer) to authenticated;
grant execute on function public.check_in_attendance(bigint, text) to authenticated;
grant execute on function public.coach_session_qr(bigint) to authenticated;
